language: java
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
    secure: wkh0c7GMM2ykRrNAVBKFmY6bWoqiy+k3fzbGOU6gSyx8FwWi6ssFVtIf3ORFBGaj8QE8jYDdKI6OrMhsL43oNyk2ljIyIzO9uinZ5FgY+nndSsCkTUTM1e9bomhx/WLtdoU1qLreNMLstgJdbxHPsaHvRFoVpi0ncBKBnJu44bgs4OMHFEZTZmK9HXH/u3uJBt9UzoGatO5s0AloPnWi6BsrBH5nxjlgdjcyZj8qCE7oipdURAQe0qmj8WYTMJB3PNHZqcpNzNUDdA0FF0yYikdDK8KkZnIw69Dk+2i7Ukb1fv4oi5TTV8/c379uL7y98Bj+X7+m+VScAJVUpBTVBaQSK20D7vKADfHltevemk+0fKN+jYC9Yrffkdw5m4qeUTB36XpO2r3TmaNNe113cbe6NWxFF/0sp7udC5hXz4Y1L/50BOaNdqiRV/bOOJLXhGaicCf5mQZ9XCWsiHntre2GlOxFsJHvqzyoyc6/6MoKK8WMD1A53au8KR7Y8vev64ullaFh8uTSJSM4uJI38zo2azvD8fUWIEww5mkC3ofmbYpEwO2M9VetUgdo0JwmmBFs0ZChiGZ0riGBol0QcNMSmGL6VAfpoNIVG9VsqaMa1swB8bS5WMVfME6lFznYqrmjpjBn4tvdvnVpOuwa+phKG3emtvujjwNKqI8kxPU=
